<a href="https://colab.research.google.com/github/geniusrusho/perceptron/blob/main/Perceptronimplementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import os

import pandas as pd
import numpy as np
import seaborn as sns
import joblib
from  matplotlib.colors import  ListedColormap
import matplotlib.pyplot as plt

plt.style.use("fivethirtyeight")


In [6]:
class Perceptron:
     def __init__(self,eta: float=None, epochs: int=None):
       self.weights = np.random.randn(3) * 1e-4
       training = (eta is not None) and (epochs is not None)
       if training:
         print(f"initial weights before training: \n{self.weights}")
         self.eta = eta
         self.epochs = epochs
     def _z_outcome(self, inputs, weights):
       return np.dot(inputs, weights)
     def activation_function(self,z):
        return np.where(z > 0,1,0)
     def fit(self, X,y):
       self.X = X
       self.y = y

       X_with_bias = np.c_[self.X, -np.ones((len(self.X), -1))]
       print(f"X with bias: \n{X_with_bias}")

       for epoch in range(self.epochs):
         print("--"*10)
         print(f"for epoch >> {epoch}")
         print("--"*10)


         z = self._z_outcome(X_with_bias, self.weights)
         y_hat = self.activate_function(z)
         print(f"prediced value after forward pass: \n{y_hat}")
         self.error = self.y - y_hat
         print(f"error: \n{self.error}")

         self.weights = self.weights + self.eta * np.dot(X_with_bias.T,self.error)
         print(f"updated weights after epoch: {epoch}/{self.epochs}: \n{self.weights}")
         print("##"*10)


     def predict(self, X):
       X_with_bias = np.c_[self.X, -np.ones((len(X), 1))]
       z = self.z_outcome(X_with_bias, self.weights)
       return self.activation_function(z)

     def total_loss(self):
       total_loss = np.sum(self.error)
       print(f"\ntotal loss: {total_loss}\n")
       return total_loss
     def _create_dir_return_path(self):
       os. makedirs(model_dir, exist_ok=True)
       return os.path.join(model_dir, filename)
       joblib.dump(self, model_file_path)


     def save(self, filename, model_dir=None):
       if model_dir is not None:
          model_file_path = self._create_dir_return_path(model_dir, filename)
          joblib.dump(self, model_file_path)
       else:
         model_file_path = self._create_dir_return_path("model", filename)
         joblib.dump(self,model_file_path)
     
     def load(self,model_file_path):
       return joblib.load(filepath)

       

    
     


In [11]:
def prepare_data(df, target_col="y"):
  X = df.drop("y", axis=1)

  y = df["y"]

  return X,y

In [8]:
import pandas as pd

AND = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,0,0,1]
}
df_AND = pd.DataFrame(AND)
df_AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [15]:
X, y = prepare_data(df_AND)

ETA = 0.1
EPOCHS = 10

model_and = Perceptron(eta=ETA, epochs=EPOCHS)


initial weights before training: 
[6.66793443e-05 4.57346121e-06 1.05051153e-04]


In [17]:
OR = {
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y" :[0,1,1,1]
}
df_OR = pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [19]:
X,y = prepare_data(df_OR)
ETA = 0.1
EPOCHS = 10
model_or = Perceptron(eta=ETA,epochs=EPOCHS)




initial weights before training: 
[-1.05153885e-04 -8.16233208e-05 -4.11422425e-05]


In [20]:
XOR = {
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y" :[0,1,1,1]
}
df_XOR = pd.DataFrame(OR)
df_XOR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [21]:
X,y = prepare_data(df_XOR)
ETA = 0.1
EPOCHS = 10
model_XOR = Perceptron(eta=ETA,epochs=EPOCHS)




initial weights before training: 
[ 2.64216243e-05 -6.58959973e-05  3.49263928e-06]
